### ISSUE TITLE
config-template.py fails

### ISSUE THREAD

**Issue by Feder1co5oave** [jswidler/elasticsearch-kubed#5]
I'm running python 3.6 on Ubuntu:
~~~
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
~~~

and I get the following error:

~~~
config-templates.py 
These scripts will create configuration files to set up an Elasticsearch cluster in Kubernetes.
Enter a kubernetes namespace for the elasticsearch cluster (default='default'): 
Enter a name for the elasticsearch cluster (default='my-es-cluster'): 
Select the node size: 
1: minikube
2: 4cpu X N
3: 8cpu X N
4: 16cpu X N
[1-4]:  (default='2'): 2
Enter the number of nodes (2-9) (default='2'): 4
Enter the data volume size in GB [10-9999] (default='250'): 50
Using keys and certs for Logstash found in clusters/default/logstash-ssl-keys.
Would you like to configure oauth2_proxy to authorize a GitHub team? (y/N): 
Traceback (most recent call last):
  File "config-templates.py", line 185, in <module>
    main()
  File "config-templates.py", line 169, in main
    output = jinja_env.get_template(template).render(context)
  File "/home/federico/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/federico/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/federico/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/federico/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "templates/6_logstash/logstash-pipelines.yml", line 9, in top-level template code
    {{ inc('6_logstash/logstash.conf')|indent(first=true) }}
TypeError: do_indent() got an unexpected keyword argument 'first'
~~~

which seems to be caused by this line in the pipeline template:
https://github.com/jswidler/elasticsearch-kubed/blob/b3446c42a30d5ad408e359d10c275a256ef40a68/templates/6_logstash/logstash-pipelines.yml#L9

I haven't tried upgrading to Python 3.7, that might solve the problem but ubuntu installs 3.6 by default. I'm just letting you know of the issue.

---

Just by looking at the documentation of jinja, I can see they broke backward compatibility by renaming `firstIndent` to `first`, somewhere along the release process.

Substituting `first` back to `indentfirst` solves the issue for me.

**Comment by nerusnayleinad** [comment]
$ ./config-templates.py
  File "./config-templates.py", line 51
    print(f"Using keys and certs for Logstash found in {cert_dir}.")
                                                                  ^
SyntaxError: invalid syntax

**Comment by jswidler** [comment]
@nerusnayleinad - you are probably using python 2 and not python 3?  Your problem is different from the open issue.

**Comment by vishwanathj** [comment]
> $ ./config-templates.py
> File "./config-templates.py", line 51
> print(f"Using keys and certs for Logstash found in {cert_dir}.")
> ^
> SyntaxError: invalid syntax

I am running into the above issue as well that nerusnayleinad has run into, how does one go about resolving this? thanks
What specific version of python should be used to run the script? 3.3.6? 3.4.3?...

**Comment by eslam-adel92** [comment]
I have the same issue here while I'm using python3

$ ./config-templates.py
File "./config-templates.py", line 51
print(f"Using keys and certs for Logstash found in {cert_dir}.")
^

**Comment by jswidler** [comment]
Looks like your guys problem is the f string syntax introduced in python 3.6

https://realpython.com/python-f-strings/

If you don't want to update python, you can easily change the print string, something like
```
print("Using keys and certs for Logstash found in "+{cert_dir + ".")```
should probably work

**Comment by jswidler** [comment]
Looks like the fstring issue is more common, but it is different from the initial poster's issue and solution.  I'm leaving this open for others to find it in case they run into similar problems.

**Comment by eslam-adel92** [comment]
Hello Guys I solved the issue of:

$ ./config-templates.py
File "./config-templates.py", line 51
print(f"Using keys and certs for Logstash found in {cert_dir}.")
^
here are the stpes:
1- install python 3.6
2- change the first line from: "#!/usr/bin/env python3" to "#!/usr/bin/env python3.6"
3- install jinja2 module by running "pip install jinja2" this will install it at the path "$HOME/.local/lib/python3.5/site-packages/jinja2/"
4- copy this directory to the path "/usr/lib/python3/dist-packages/jinja2/"

and run the script it will work fine with you :) :)

**Comment by devopsdymyr** [comment]
> Hello Guys I solved the issue of:
> 
> $ ./config-templates.py
> File "./config-templates.py", line 51
> print(f"Using keys and certs for Logstash found in {cert_dir}.")
> ^
> here are the stpes:
> 1- install python 3.6
> 2- change the first line from: "#!/usr/bin/env python3" to "#!/usr/bin/env python3.6"
> 3- install jinja2 module by running "pip install jinja2" this will install it at the path "$HOME/.local/lib/python3.5/site-packages/jinja2/"
> 4- copy this directory to the path "/usr/lib/python3/dist-packages/jinja2/"
> 
> and run the script it will work fine with you :) :)

I have tried to follow this steps but not working.
![Screenshot from 2019-09-26 07-48-44](https://user-images.githubusercontent.com/41105507/65653242-18c41100-e032-11e9-97cd-16c5b85819ff.png)
![Screenshot from 2019-09-26 07-41-32](https://user-images.githubusercontent.com/41105507/65653243-18c41100-e032-11e9-81ec-c494d99f8be2.png)

**Comment by jswidler** [comment]
@devopsdymyr step 1 says `install python 3.6`, but your screenshots show version `3.5.2`.
